name: VulnAlerts

on: 
  push:
     branches: [ master ]
    
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prune Docker System
      run: docker system prune --all --force

    - name: Build Docker Image
      run: docker build --no-cache -t vulnalerts-image .

    - name: Run VulnAlerts
      run: docker run --name vulnalerts-container -e SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }} vulnalerts-image

    - name: Done
      run: echo 'Done'
