name: VulnAlerts

on: 
  schedule:
    - cron: '*/10 * * * *'

jobs:
  alert:
    runs-on: cverunner
    steps:
    - uses: actions/checkout@master
    - uses: sholguin/vulnalerts@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: done
      run: echo 'done'
